"""Instaladores user-space usados pelo bootstrap."""

from .core import (
    AWS_LINUX_INSTALL_URL,
    AWS_WINDOWS_INSTALL_URL,
    FNM_VERSION,
    INSTALLERS,
    InstallContext,
    InstallResult,
    InstallerError,
    DependencyInstaller,
    download_file,
    ensure_path_entry,
    install_aws_cli,
    install_codebase_memory,
    install_crwl,
    install_dependencies,
    install_docling,
    install_fnm,
    install_git,
    install_npm_global,
    install_node,
    install_pandoc,
    install_playwright,
    install_pipx,
    install_pytest,
)

__all__ = [
    "AWS_LINUX_INSTALL_URL",
    "AWS_WINDOWS_INSTALL_URL",
    "FNM_VERSION",
    "INSTALLERS",
    "InstallContext",
    "InstallResult",
    "InstallerError",
    "DependencyInstaller",
    "download_file",
    "ensure_path_entry",
    "install_aws_cli",
    "install_codebase_memory",
    "install_crwl",
    "install_dependencies",
    "install_docling",
    "install_fnm",
    "install_git",
    "install_npm_global",
    "install_node",
    "install_pandoc",
    "install_playwright",
    "install_pipx",
    "install_pytest",
]
